# if on windows:
[shell]
program = "C:\\Windows\\System32\\wsl.exe"
args = ["-d", "Ubuntu"]

[font]
size = 14

[font.normal]
family = "Hack Nerd Font"

[window]
opacity = 0.90
decorations = "Buttonless"
option_as_alt = "Both"

[colors.primary]
# dark
background = "#1f2937"

# light
# background = "#fef6fa"
# foreground = "#2a2b33"
